  - name: Add key
    apt_key: 
     url: "{{ cassandra_repo_key }}"
     state: present
         
  - name: Add cassandra repo
    apt_repository: 
      repo: "{{ cassandra_repo }}"
      state: present
      filename: cassandra.sources.list

  - name: Install cassandra
    apt: 
      name: cassandra=3.11.11
      state: present
      update_cache: yes

  - name: Enable service and start at boot
    service:
     name: cassandra
     enabled: yes
     state: started
  
  - name: copying the rack and datacenter config file if we are having cluster
    template:
     src: "cassandra-rackdc.properties.j2"
     dest: "{{ cassandra_root_dir }}/cassandra-rackdc.properties"
     owner: "root"
     group: "root"
     mode: "0644"
     backup: true
    when: ( cassandra_cluster_size | int ) > 1

  - name: config | Configuring Cassandra
    template:
     src: "cassandra.yaml.j2"
     dest: "{{ cassandra_root_dir }}/cassandra.yaml"
     owner: "root"
     group: "root"
     mode: 0644
     backup: true

  - name: Stop cassandra nodes if started
    service:
     name: cassandra
     state: stopped

  - name: Wait for cassandra to stop
    wait_for:
     state: stopped
     port: 9042
     delay: 10
     sleep: 5

  - name: Restart Cassandra seeds
    service:
     name: cassandra
     state: restarted
    delegate_to: "{{ item }}"
     # ansible won't throw index out of bound exception.
    with_items: "{{ groups['db'][:2] }}"
    run_once: true


  - name: Wait for cassandra seeds to start
    wait_for:
      state: started
      port: 9042
      delay: 10
      sleep: 5
    delegate_to: "{{ item }}"
    #ansible won't throw index out of bound exception.
    with_items: "{{ groups['db'][:2] }}"
    run_once: true

  - name: Restart Cassandra nodes
    service:
      name: cassandra
      state: restarted
    delegate_to: "{{ item }}"
    with_items: "{{ groups['db'][2:] }}"
    when: groups['cassandra'] | length > 2
    run_once: true

  - name: wait for cassandra to be up and running
    wait_for:
      host: "{{ ansible_default_ipv4.address }}"
      port: 9042
      delay: 30 
    
